# path to the python scripts used in the workflow
# path_to_scripts: "/storage/biomeds/projects/neurorad-drg-dti/snakemake_code/"
path_to_scripts: "/Users/Robin/Documents/Studium/Master_Bio/Masterarbeit/Skripte/Snakemake_skripte/"

# parameters for the fslroi commands; start and end values for x, y, z, and temporal dimension
ROI_params: "36 52 20 80 0 -1 0 -1"
ROI_old: "35 60 33 60 0 -1 0 -1"

# max runtime for each job via slurm
cluster:
  sbatch_args:
    - "--time=16:00:00"

